# Generated by Django 4.2.20 on 2025-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_pizza_slug_alter_pizza_image_alter_pizza_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
