# Generated by Django 4.2.20 on 2025-04-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.category'),
        ),
    ]
