# Generated by Django 4.2.20 on 2025-04-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_pizza_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='is_available',
            field=models.BooleanField(choices=[(0, 'Нет в наличии'), (1, 'Есть в наличии')], default=0),
        ),
    ]
