# Generated by Django 4.2.20 on 2025-04-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_alter_pizza_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
