# Generated by Django 4.2.20 on 2025-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_tagpost_pizza_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='homepage.tagpost'),
        ),
    ]
