# Generated by Django 4.2.20 on 2025-04-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_alter_pizza_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='homepage.pizzahistory'),
        ),
    ]
