# Generated by Django 4.2.20 on 2025-05-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_pizzahistory_pizza_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='homepage.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='homepage.pizzahistory', verbose_name='История создания'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='is_available',
            field=models.BooleanField(choices=[(False, 'Нет в наличии'), (True, 'Есть в наличии')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='homepage.tagpost', verbose_name='Тэги'),
        ),
    ]
