# Generated by Django 4.2.20 on 2025-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='diameter',
            field=models.PositiveIntegerField(default=30, verbose_name='Диаметр (см)'),
        ),
    ]
