# Generated by Django 4.2.20 on 2025-05-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_alter_pizza_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='history_text',
            field=models.TextField(blank=True, verbose_name='История создания'),
        ),
    ]
