# Generated by Django 4.2.20 on 2025-05-04 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_uploadfiles_pizza_uploaded_at_alter_pizza_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfiles',
            options={'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
        ),
    ]
