# Generated by Django 4.2.20 on 2025-05-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_pizza_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='photo',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
