# Generated by Django 4.2.20 on 2025-05-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_remove_pizza_photo_alter_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='photo',
        ),
    ]
