# Generated by Django 4.2.20 on 2025-05-22 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0024_remove_pizza_photo_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizzas', to=settings.AUTH_USER_MODEL),
        ),
    ]
