# Generated by Django 4.2.20 on 2025-05-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0025_pizza_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='author',
        ),
    ]
