# Generated by Django 4.2.20 on 2025-06-08 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0027_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_pizzas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pizza',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pizzas', to=settings.AUTH_USER_MODEL),
        ),
    ]
