# Generated by Django 4.2.20 on 2025-06-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
